---
title: "HW5"
author: "Bohan Zhu"
date: "2025-11-18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)
```

```{r,include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  fig.retina = 2,
  dpi = 320
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
set.seed(1)
```

## Problem 1

```{r}
homicides = 
  read_csv("data/homicide-data.csv", 
           na = c("NA",".","","Unknown")) |>
  janitor::clean_names() 

homicide_df = 
  homicides |> 
  mutate(
    city_state = str_c(city, ", ", state),
    status = ifelse(disposition == "Closed by arrest", 1, 0)
  ) |> 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race == "White" | victim_race == "Black"
  )
```

```{r}
baltimore_df <- homicide_df |> 
  filter(city_state == "Baltimore, MD") |> 
  select(status, victim_age, victim_race, victim_sex)
```

```{r}
fit_logistic = 
  baltimore_df |> 
  glm(status ~ victim_age + victim_race + victim_sex, data = _, 
      family = binomial())

fit_logistic |> 
  broom::tidy(conf.int = TRUE, exponentiate = TRUE) |> 
  filter(term == "victim_sexMale") |> 
  select(estimate, conf.low, conf.high) |> 
  knitr::kable(digits = 3)
```

```{r}
fit_city_glm = function(df) {
  glm(status ~ victim_age + victim_race + victim_sex,
      data = df, family = binomial())
}

city_or_df =
  homicide_df |>
  nest(data = -city_state) |> 
  mutate(
    fits = map(data, fit_city_glm),
    results = map(fits, ~ broom::tidy(.x, conf.int = TRUE, exponentiate = TRUE))
  ) |>
  unnest(results) |>
  filter(term == "victim_sexMale") |>
  select(city_state, estimate, conf.low, conf.high)

city_or_df
```

```{r}
city_or_df |> 
  mutate(
    city_state = fct_reorder(city_state, estimate)
    ) |>
  ggplot(aes( x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(size = 5,angle = 90,hjust = 1)) +
  coord_flip() +
  ggtitle("Odds Ratio for Solving homicides among sex")
```

## Problem 2

```{r}
data("weather_df")

weather_df |> 
  select(tmax, tmin, prcp) |> 
  drop_na()
```

```{r}
weather_bootstrap_results = 
  weather_df |> 
  bootstrap(n = 5000) |> 
  mutate(
    df = map(strap, as_tibble),
    fits = map(df, \(df) lm(tmax ~ tmin + prcp, data = df)),
    results_r2 = map(fits, broom::glance),
    results_coef = map(fits, broom::tidy)
  ) |> 
  select(.id, results_r2, results_coef)
```

First, let's look at the distribution of $r^2$. 

```{r}
r2_dist =
  weather_bootstrap_results |> 
  unnest(results_r2) |> 
  select(.id, r.squared) 

r2_dist |> 
  ggplot(aes(x = r.squared)) +
  geom_density() +
  labs(title = "Bootstrap distribution of R^2",
       x = "R^2")
```

Then, look at the confidence interval for $r^2$$

```{r}
r2_dist |> 
  summarize(
    ci_lower = quantile(r.squared, 0.025),
    ci_upper = quantile(r.squared, 0.975)
  )
```

Similarly, we can look at the distribution of $\frac{\hat{\beta_{1}}}{\hat{\beta_{2}}}$

```{r}
coef_dist =
  weather_bootstrap_results |> 
  unnest(results_coef) |> 
  filter(term %in% c("tmin", "prcp")) |> 
  select(.id, term, estimate) |> 
  pivot_wider(names_from = term, values_from = estimate) |> 
  mutate(beta_ratio = tmin / prcp)

coef_dist |> 
  ggplot(aes(x = beta_ratio)) +
  geom_density() +
  labs(title = "Bootstrap distribution of beta1 / beta2",
       x = "beta1 / beta2")
```

We may also look at the confidence interval for $\frac{\hat{\beta_{1}}}{\hat{\beta_{2}}}$.

```{r}
coef_dist |> 
  summarize(
    ci_lower = quantile(beta_ratio, 0.025),
    ci_upper = quantile(beta_ratio, 0.975)
  )
```

## Problem 3
